@startuml database-ER

' Entities

object Profile {
    <u>nickname: str</u>
    creation: date
}

object Session {
    <u>id: int > 0</u>
    start: timestamp
}

object Scene {
    <u>ord: int > 0</u>
    name: scene
    time_in: interval
    max_wait: real
    avg_wait: real
}

object Quest {
    <u>id: int > 0</u>
    goal: int
    start: timestamp
    end: timestamp
    result: int 0..1
    hp: int
    grid: str
}

object Operation {
    <u>ord: int > 0</u>
    type: operation
    primary_cell: cell
    secondary_cell: cell
}

' Relationship

Profile "0..*" -- "1..1" Session : plays

Session "0..*" -- "1..1" Quest : has

Session "1..*" -- "<u>1..1</u>" Scene : takes

Quest "0..*" -left- "<u>1..1</u>" Operation : performs

@enduml