@startuml database-ER

' Entities

object Profile {
    {static} nickname: str
    creation: date
}

object Session {
    start: timestamp
    end: timestamp
    max_wait: real
    avg_wait: real
}

object Quest {
    goal: int
    start: timestamp
    end: timestamp
    result: int 0..1
    hp: int
    grid: str
}

object Operation {
    type: operation
    ord: int > 0
    primary_cell: cell
    secondar_cell: cell
}

' Relationship

Profile "0..*" -- "1..1" Session : plays

Session "0..*" -- "1..1" Quest : has

Operation "0..*" -- "0..*" Quest : performs

@enduml