@startuml architecture

database Statistics

package "Game" {
    [menu]
    [quest]
    [exit]
    [settings]
    [profiles]
}

[menu] -down-> [quest] : play
[menu] -down- [exit]
[menu] -down- [settings]
[menu] -down- [profiles] : switch

[settings] -- [graphic]
[settings] -- [input mapping]

[quest] -> [menu] : lost/won

[profiles] -left- Statistics
[quest]    -left- Statistics : write

Actor User

User -right-> [menu] : Open

@enduml