@startuml database-ER

' Entities

object Profile {
    <u>nickname: str</u>
    creation: timestamp
}

object Session {
    <u>id: int > 0</u>
    start: timestamp
}

object Scene {
    <u>ord:   int > 0</u>
    name:        scene
    startstamp:  timestamp
    endstamp:    timestamp
    max_wait:    real
    avg_wait:    real
}

object Quest {
    grid: str
    goal: int
    result: int 0..1
    hp: int
}

object Operation {
    <u>ord: int > 0</u>
    type: operation
    primary_cell: cell
    secondary_cell: cell
}

' Relationship

Profile "0..*" -- "1..1" Session : plays

Session "1..*" -- "<u>1..1</u>" Scene : has

Scene "0..1" -- "<u>1..1</u>" Quest : is

Quest "0..*" -left- "<u>1..1</u>" Operation : performs

@enduml