@startuml message-sequence-chart

participant Menu
participant Quest
participant Grid
control Input
participant Database

Menu -> Quest : Play

== Setup Game ==
activate Quest
Quest -> Quest : Generate "quest"\nnumber
Quest -> Grid : Generate grid 
Grid -> Database : Store new game

== Loop == 
activate Grid
Grid -> Input : Wait response
Input -> Grid : Give Input
Grid -> Grid : Process Input

== End ==
Grid -> Quest : 1 cell remaining
return Grid
return Quest

@enduml