@startuml usecase

Actor Player
Actor System

Player -down-> (Score) : See
Player -down-> (Score) : Reset
Player -right-> (Profile) : Create
Player -right-> (Profile) : Edit
Player -right-> (Profile) : Delete

System -down-> (Score) : Save/Load/Show
System -left-> (Profile) : Save/Load

Player -right-> (Game) : Play
Player -right-> (Game) : Pause
Player -right-> (Game) : Stop

System --> (Game) : Save

@enduml